apiVersion: v2
name: cloudstack-csi
description: A Helm chart for CloudStack CSI driver
type: application
version: 3.0.1
appVersion: 3.0.0
sources:
  - https://github.com/cloudstack/cloudstack-csi-driver
keywords:
  - csi
  - cloudStack
maintainers:
  - name: hrak
  - name: FarnazBGH
  - name: lanord
